Repository alphagov/govuk-infrastructure, pull requests merged in 2025-08, with the labels that each got.

#2496 Update Helm release argo-cd to v8.2.5
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2486 Update Terraform tfe to v0.68.2
  terraform/deployments/govuk-publishing-infrastructure/main.tf
  terraform/deployments/tfc-configuration/provider.tf
Labels: dependencies, renovate

#2487 Update Terraform aws to v6.7.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/release/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2493 Update Terraform google to ~> 6.46.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2523 Update Terraform fastly to v8
  terraform/deployments/datagovuk-infrastructure/main.tf
  terraform/deployments/govuk-publishing-infrastructure/main.tf
  terraform/deployments/mobile-backend/main.tf
Labels: dependencies, renovate

#2542 Update Terraform aws to v6.8.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/release/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2527 Update Terraform google to ~> 6.48.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2568 Update dflook/terraform-version digest to c397d40
  .github/workflows/ci-terraform.yml
Labels: dependencies, renovate

#2571 Update pre-commit hook antonbabenko/pre-commit-terraform to v1.100.0
  .pre-commit-config.yaml
Labels: dependencies, renovate

#2570 Update Helm release argo-workflows to v0.45.22
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2539 Create interruption issue template
  .github/ISSUE_TEMPLATE/interruption.md
Labels: Interruption

#2619 Update Terraform google to ~> 6.49.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2651 Document adding new repos to GOV.UK GitHub Infrastructure config
  terraform/deployments/github/README.md
Labels: unplanned

#2679 Update 'Report GitHub workflow run failure to Slack' README
  .github/actions/report-run-failure/README.md
Labels: unplanned
