Repository alphagov/govuk-infrastructure, pull requests merged in 2025-03, with the labels that each got.

#1760 Update Action Lint checker to v1.7.7
  .github/actions/actionlint/action.yml
Labels: dependencies, github_actions

#1750 Document Graviton switchover decision
  docs/architecture/decisions/0011-use-graviton-for-compute-instances.md
Labels: documentation, ARM

#1847 Remove unnecessary Sentry teams
  terraform/deployments/sentry/locals.tf
  terraform/deployments/sentry/main.tf
Labels: KTLO

#1886 Improve report-run-failure README
  .github/actions/report-run-failure/README.md
  .github/actions/report-run-failure/action.yml
Labels: feature

#1902 Enable EKS Access Entries support (in Integration)
  terraform/deployments/tfc-configuration/variables-integration.tf
Labels: security, k8s
