Repository alphagov/govuk-infrastructure, pull requests merged in 2025-05, with the labels that each got.

#2074 Update Terraform google to ~> 6.33.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2079 Harden security context for filebeat DaemonSet
  terraform/deployments/cluster-services/logging.tf
Labels: security

#2104 EKS Auth to API exclusively on Integration first
  terraform/deployments/ephemeral/tfe.tf
  terraform/deployments/tfc-configuration/variables-integration.tf
Labels: security

#2088 Update Terraform aws to v5.97.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/release/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2096 Update Terraform google to ~> 6.34.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2075 Update Helm release argo-workflows to v0.45.14
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2099 Update aws-actions/configure-aws-credentials action to v4.2.0
  .github/workflows/mirror-repos.yml
Labels: dependencies, renovate

#2065 Update Helm release argo-cd to v7.9.1
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2122 Switch all environments to EKS API auth only
  terraform/deployments/cluster-infrastructure/variables.tf
  terraform/deployments/ephemeral/tfe.tf
  terraform/deployments/tfc-configuration/release.tf
  terraform/deployments/tfc-configuration/variables-integration.tf
Labels: security

#2114 Update Helm release aws-load-balancer-controller to v1.13.0
  terraform/deployments/cluster-services/aws_lb_controller.tf
Labels: dependencies, renovate

#2101 Update Helm release aws-ebs-csi-driver to v2.43.0
  terraform/deployments/cluster-services/aws_ebs_csi_driver.tf
Labels: dependencies, renovate

#2121 Update actions/dependency-review-action digest to 38ecb5b
  .github/workflows/dependency-review.yml
Labels: dependencies, renovate

#2105 Update Helm release external-secrets to v0.16.2
  terraform/deployments/cluster-services/external_secrets.tf
Labels: dependencies, renovate

#2135 Upsize and Upgrade the Staging Pub API RDS.
  terraform/deployments/tfc-configuration/variables-staging.tf
Labels: reliability

#2085 Harden Dex Pods
  terraform/deployments/cluster-services/dex.tf
Labels: security

#2139 Update actions/dependency-review-action digest to da24556
  .github/workflows/dependency-review.yml
Labels: dependencies, renovate

#2156 Update Helm release argo-workflows to v0.45.15
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2160 Update Terraform aws to v5.98.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/release/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2147 Update Terraform hashicorp/terraform to ~> 1.12.0
  terraform/deployments/tfc-configuration/modules/search-api-v2/main.tf
Labels: dependencies, renovate

#2140 Update Terraform google to ~> 6.35.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2190 Update Terraform google to ~> 6.37.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2204 Update Terraform tfe to v0.66.0
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/elasticache/main.tf
  terraform/deployments/gcp-search-api-v2/main.tf
  terraform/deployments/gcp-search-api-v2/modules/search-api-v2/main.tf
  terraform/deployments/govuk-publishing-infrastructure/main.tf
  terraform/deployments/release/main.tf
  terraform/deployments/tfc-aws-config/provider.tf
  terraform/deployments/tfc-bootstrap/provider.tf
  terraform/deployments/tfc-configuration/provider.tf
Labels: dependencies, renovate

#2205 Update docker/build-push-action digest to 2634353
  .github/workflows/build-and-push-image.yml
  .github/workflows/build-and-push-multiarch-image.yml
Labels: dependencies, renovate
