Repository alphagov/govuk-infrastructure, pull requests merged in 2025-04, with the labels that each got.

#1931 Skip final snapshots for RDS read replicas
  terraform/deployments/rds/rds.tf
Labels: KTLO

#1966 Add labels to Renovate PRs
  renovate.json
Labels: KTLO

#1963 Update actions/dependency-review-action digest to 67d4f4b
  .github/workflows/dependency-review.yml
Labels: dependencies, renovate

#1910 Create EKS Access Entries for Developers
  terraform/deployments/cluster-services/aws_auth_configmap.tf
  terraform/deployments/cluster-services/eks_access.tf
Labels: security

#1974 Update Terraform restapi to v2
  terraform/deployments/search-api-v2/main.tf
  terraform/deployments/search-api-v2/modules/control/main.tf
  terraform/deployments/search-api-v2/modules/serving_config/main.tf
Labels: dependencies, renovate

#1985 Devs' Access Entries had no EKS Policy Associated
  terraform/deployments/cluster-services/eks_access.tf
Labels: security, k8s

#1987 Grant EKS Devs Access to View Cluster Insights
  terraform/deployments/cluster-services/eks_access.tf
Labels: k8s

#1927 Update Terraform google to ~> 6.29.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#1999 Update actions/setup-node digest to 49933ea
  .github/actions/setup-node/action.yml
  .github/workflows/publish-npm-package.yml
Labels: dependencies, renovate

#2006 Update pre-commit hook antonbabenko/pre-commit-terraform to v1.99.0
  .pre-commit-config.yaml
Labels: dependencies, renovate

#1998 Update Helm release argo-cd to v7.8.26
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2015 Update Terraform google to ~> 6.30.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#1991 Update Helm release argo-bootstrap-ephemeral to v0.0.11
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#1916 Update Helm release aws-ebs-csi-driver to v2.41.0
  terraform/deployments/cluster-services/aws_ebs_csi_driver.tf
Labels: dependencies, renovate

#2021 Update Helm release cluster-secret-store to v0.2.0
  terraform/deployments/cluster-services/external_secrets.tf
Labels: dependencies, renovate

#2023 Update Helm release external-secrets to v0.16.1
  terraform/deployments/cluster-services/external_secrets.tf
Labels: dependencies, renovate

#2035 Update Helm release argo-cd to v7.8.28
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2043 Update github/codeql-action digest to 28deaed
  .github/workflows/brakeman.yml
  .github/workflows/codeql-analysis.yml
Labels: dependencies, renovate

#2042 Update Terraform google to ~> 6.31.0
  terraform/deployments/ga4-analytics/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2034 Update Terraform tfe to v0.65.2
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/elasticache/main.tf
  terraform/deployments/gcp-search-api-v2/main.tf
  terraform/deployments/gcp-search-api-v2/modules/search-api-v2/main.tf
  terraform/deployments/govuk-publishing-infrastructure/main.tf
  terraform/deployments/tfc-aws-config/provider.tf
  terraform/deployments/tfc-bootstrap/provider.tf
  terraform/deployments/tfc-configuration/provider.tf
Labels: dependencies, renovate

#2033 Update Terraform aws to v5.95.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2046 Update Helm release argo-bootstrap-ephemeral to v0.1.0
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate

#2047 Add 'Platform Engineering onboarding' issue template
  .github/ISSUE_TEMPLATE/onboarding.md
Labels: KTLO

#2052 Update Terraform aws to v5.96.0
  terraform/deployments/cluster-infrastructure/main.tf
  terraform/deployments/cluster-services/main.tf
  terraform/deployments/search-api-v2/main.tf
Labels: dependencies, renovate

#2062 Update Terraform sentry to v0.14.5
  terraform/deployments/sentry/provider.tf
Labels: dependencies, renovate

#2068 Grant Dev Role access to Ingresses
  terraform/deployments/cluster-services/eks_access.tf
Labels: security, k8s

#2071 Update Helm release argo-bootstrap-ephemeral to v0.1.1
  terraform/deployments/cluster-services/argo.tf
Labels: dependencies, renovate
